# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_accessrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(max_length=255),
        ),
    ]
